language: python
python:
  - 3.8
branches:
  only:
    - develop
    - master
before_install:
  - pip install -U pip
  - pip install -e .
  - sudo apt-get update && sudo apt-get -y install libportaudio19-dev
install:
  - pip install -r requirements.txt
script:
  - python -m build
after_failure:
  - echo "Build verification failed" && exit 1
after_script:
  - cd dist && pip install *.whl
after_deploy:
  - echo "All done"