language: python
python:
  - 3.8
branches:
  only:
    - develop
    - master
before_install:
  - pip install -U pip
  - sudo apt-get update && sudo apt-get install portaudio19-dev python-pyaudio python3-pyaudio
  - pip install -e .
install:
  - pip install -r requirements.txt
script:
  - python -m build
after_failure:
  - echo "Build verification failed" && exit 1
after_script:
  - cd dist && pip install *.whl
after_deploy:
  - echo "All done"